Maintenance page init
G-Techs/yokaa-frontend pull request #44
Opened 2022-06-23 15:44 UTC by Francois18

The maintenance page is initialized and can be accessed by routing to  **/maintenance**

![Screenshot (2)](https://user-images.githubusercontent.com/79960710/175339927-1d5d5ee3-bc35-4f4b-879e-7d1fbee41ba7.png)
![Screenshot (3)](https://user-images.githubusercontent.com/79960710/175339965-9af37a0f-348e-4af2-b297-2016c2a0dc63.png)

2022-06-23 20:16 UTC, Jonath-z requested changes
kindly applie these changes

when you already create the folder like **Maintenace** don't name the main file inside `Maintenace` again. just name it `index.jsx`. this can be applied in `components/Maintenance`

2022-06-23 20:16 UTC, Jonath-z commented on components/Maintenance/Maintenance.jsx
> +                    <img src="https://templates.iqonic.design/muzik/html/images/error/02.png" alt="logo" className='sm:h-56 h-28  mb-6' />
image or svg here , dowload it then use it

2022-06-23 20:16 UTC, Jonath-z commented on components/Maintenance/Maintenance.jsx
> +                                < LayoutTopLine size={54} />
remove empty space

2022-06-23 20:16 UTC, Jonath-z commented on components/Maintenance/Maintenance.jsx
> +                        <div className='px-4 py-2 flex flex-col justify-center  items-center '>
create a card for this maintance motifs as they have the same design.

2022-06-26 09:16 UTC, Jonath-z approved these changes
LGTM

2022-06-26 09:17 UTC, Jonath-z commented
try to resolve conflict

2022-06-26 11:29 UTC, Francois18 commented
> try to resolve conflict

resolved

2022-06-27 03:29 UTC, merged