add confirm email page
G-Techs/yokaa-frontend pull request #48
Opened 2022-06-25 16:34 UTC by Derick1530

2022-06-27 12:36 UTC, Jonath-z reviewed
KIndly Apply these changes

2022-06-27 12:36 UTC, Jonath-z commented on components/Auth/ConfirmEmail/index.jsx
> +                            <img alt='Pic' src={'https://templates.iqonic.design/muzik/html/images/login/user.png'} />
no need of `{}` here . kindly improve it

2022-06-27 12:36 UTC, Jonath-z commented on components/Auth/ConfirmEmail/index.jsx
> +                            <img className='' src='https://templates.iqonic.design/muzik/html/images/login/mail.png' alt='email' />
same thing here

2022-06-27 12:36 UTC, Jonath-z commented on components/Auth/ConfirmEmail/index.jsx
> +                        <div className='lg:w-full '>
kindly remove white space

2022-06-27 12:52 UTC, Muhindo-Galien requested changes
**Kindly, check the comment added in your code as well as 
check the responsiveness of your page.
upload its picture on both desktop and mobile view for a great review**

2022-06-27 12:52 UTC, Muhindo-Galien commented on pages/confirm-email.js
> +        <>
no need of fragment since it's a simple fragment,
kindle remove it

2022-06-27 13:09 UTC, Derick1530 commented
![Screenshot 2022-06-27 154859](https://user-images.githubusercontent.com/61876679/175948546-270eb26e-1a77-4879-9519-01372d783aa6.png)
![Screenshot 2022-06-27 160320](https://user-images.githubusercontent.com/61876679/175948662-39b7f822-a3a3-4a5a-863e-41e8a85c6dfc.png)

2022-07-06 09:01 UTC, merged

2022-07-06 09:01 UTC, Muhindo-Galien commented
LGTM